[colors]
draw_bold_text_with_bright_colors = true

[colors.bright]
black = "#fdf6e3"
blue = "#657b83"
cyan = "#586e75"
green = "#93a1a1"
magenta = "#6c71c4"
red = "#cb4b16"
white = "#002b36"
yellow = "#839496"

[colors.cursor]
cursor = "#586e75"
text = "#fdf6e3"

[colors.normal]
black = "#eee8d5"
blue = "#268bd2"
cyan = "#2aa198"
green = "#859900"
magenta = "#d33682"
red = "#dc322f"
white = "#073642"
yellow = "#b58900"

[colors.primary]
background = "#fdf6e3"
bright_foreground = "#073642"
foreground = "#657b83"

[font]
#size = 9
#size = 10
# No idea why this looks better, but it does, maybe it's some interaction with fractional scaling?
size = 10.2

[font.normal]
family = "DejaVu Sans Mono for Powerline"

[[keyboard.bindings]]
action = "Paste"
key = "V"
mode = "~Vi"
mods = "Control|Shift"

[[keyboard.bindings]]
action = "Copy"
key = "C"
mods = "Control|Shift"

[[keyboard.bindings]]
action = "SearchForward"
key = "F"
mode = "~Search"
mods = "Control|Shift"

[[keyboard.bindings]]
action = "SearchBackward"
key = "B"
mode = "~Search"
mods = "Control|Shift"

[[keyboard.bindings]]
action = "ClearSelection"
key = "C"
mode = "Vi|~Search"
mods = "Control|Shift"

[[keyboard.bindings]]
action = "PasteSelection"
key = "Insert"
mods = "Shift"

[[keyboard.bindings]]
action = "ResetFontSize"
key = "Key0"
mods = "Control"

[[keyboard.bindings]]
action = "IncreaseFontSize"
key = "Equals"
mods = "Control"

[[keyboard.bindings]]
action = "IncreaseFontSize"
key = "Plus"
mods = "Control"

[[keyboard.bindings]]
action = "IncreaseFontSize"
key = "NumpadAdd"
mods = "Control"

[[keyboard.bindings]]
action = "DecreaseFontSize"
key = "Minus"
mods = "Control"

[[keyboard.bindings]]
action = "DecreaseFontSize"
key = "NumpadSubtract"
mods = "Control"

[[keyboard.bindings]]
action = "SpawnNewInstance"
key = "T"
mods = "Control|Shift"

[window.padding]
x = 1
y = 1
